version: '3'
services:
  sslproxy:
    container_name: ${PROJECT_NAME}_sslproxy
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '${SSLPROXY_ADMIN_IP}:81:81'
      - '443:443'
    volumes:
      - ${HOST_RUN_DIR}/sslproxy/config.json:/app/config/production.json
      - ${HOST_RUN_DIR}/sslproxy/data:/data
      - ${HOST_RUN_DIR}/sslproxy/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
