version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $HOST_RUN_DIR/sslproxy/nginx:/etc/nginx/conf.d
      - $HOST_RUN_DIR/sslproxy/certbot/conf:/etc/letsencrypt
      - $HOST_RUN_DIR/sslproxy/certbot/www:/var/www/certbot
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - $HOST_RUN_DIR/sslproxy/certbot/conf:/etc/letsencrypt
      - $HOST_RUN_DIR/sslproxy/certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
