stages:
  - test
  - davical
  - testall

test:
  stage: test
  image: debian:unstable
  script:
  - apt-get update && apt-get install php php-cli phpunit -yq
  - for PHP in inc/*.php; do php -l $PHP; done;
  - phpunit --log-junit phpunit.xml tests
  artifacts:
    reports:
      junit: phpunit.xml

davical_tests:
  stage: davical
  image: debian:unstable
  artifacts:
    paths:
      - davical-master/testing/report.xml
      - apache2_log/*
    reports:
      junit: testing/report.xml
    when:
      always
  script:
    - apt-get -y update
    - bash -c 'mkdir -p /usr/share/man/man{0..10}'
    - apt-get -y install locales
    - echo "en_NZ.UTF-8 UTF-8" >> /etc/locale.gen
    - locale-gen
    - echo "LANG=en_NZ.UTF-8" > /etc/default/locale
    - apt-get -y install libdbd-pg-perl libyaml-perl php php-cli php-pgsql php-xml postgresql-client postgresql libapache2-mod-php curl xmlstarlet
    - curl 'https://gitlab.com/davical-project/davical/-/archive/master/davical-master.tar.gz' | tar zxf -
    - ln -s . awl
    - echo '127.0.1.1  regression mycaldav myempty' >> /etc/hosts
    - rm /etc/apache2/ports.conf /etc/apache2/sites-enabled/000-default.conf && touch /etc/apache2/ports.conf
    - perl -pi -E 's/\/path\/to\/awl/$ENV{PWD}/g' davical-master/testing/apache-site.conf.example
    - perl -pi -E 's/\/path\/to\/davical/$ENV{PWD}\/davical-master/g' davical-master/testing/apache-site.conf.example
    - cp davical-master/testing/apache-site.conf.example /etc/apache2/sites-enabled/davical-regression.conf
    - mkdir /etc/davical
    - cp davical-master/testing/regression-conf.php.example /etc/davical/regression-conf.php
    - ln -s /etc/davical/regression-conf.php /etc/davical/mycaldav-conf.php
    - ln -s /etc/davical/regression-conf.php /etc/davical/myempty-conf.php
    - mkdir -p /var/log/davical
    - chown www-data /var/log/davical
    - sed -i '/peer/d' /etc/postgresql/13/main/pg_hba.conf
    - echo 'local  all  all  trust' >> /etc/postgresql/13/main/pg_hba.conf
    - pg_ctlcluster 13 main start
    - su postgres -c 'createuser davical_dba --createdb --createrole --superuser'
    - su postgres -c 'createuser davical_app --superuser'
    - su postgres -c 'createuser testrunner --superuser'
    - pg_ctlcluster 13 main restart
    - a2enmod rewrite
    - apache2ctl start
    - useradd testrunner
    - chown -R testrunner davical-master/testing
    - cd davical-master/testing && su testrunner -c 'IS_CI=yes ALLSUITES="regression-suite binding carddav scheduling" ./run_regressions.sh all x'
  after_script:
    - cp -r /var/log/apache2 apache2_log
    - cp -r /var/log/davical davical_log

test_stretch:
  stage: testall
  image: debian:stretch
  script:
  - apt-get update && apt-get install php php-cli phpunit -yq
  - for PHP in inc/*.php; do php -l $PHP; done;
  - phpunit --log-junit phpunit.xml tests
  artifacts:
    reports:
      junit: phpunit.xml

test_buster_latestphp:
  stage: testall
  image: php:cli-buster
  script:
  - for PHP in inc/*.php; do php -l $PHP; done;
  artifacts:
    reports:
      junit: phpunit.xml
