# manage-order 1000
version: '3.3'

services:
  admin:
    container_name: ${PROJECT_NAME}_${CUSTOMS}_admin
    build: $ODOO_HOME/images/admin
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - $ODOO_HOME/images/admin/src:/opt/src
      - /var/run/docker.sock:/var/run/docker.sock
      - $ODOO_HOME:/opt/odoo
      - $ODOO_HOME/images/odoo/bin/update_modules.py:/update_modules.py
    environment:
        DBNAME: admin
        LOGLEVEL: info
        INSTANCES_FILE: /opt/odoo/run/odoo_instances
        ODOO_HOME: /opt/odoo
        CUSTOMS: $CUSTOMS
        MINIMUM_CONTAINERS: proxy,redis
        DEPLOY_BRANCH: deploy
        MASTER_BRANCH: master
    env_file:
      - $HOST_RUN_DIR/settings
    command: /rootrun.sh
    ports:
       - "4488:8069"
