volumes:
    mongodb_volume:
services:
    mongodb:
        image: mongo
        restart: "unless-stopped"
        volumes:
            - mongodb_volume:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongouser1
            MONGO_INITDB_ROOT_PASSWORD: topSecretDontTel!l1234
    mongo-express:
        image: mongo-express
        restart: "unless-stopped"
        #ports: 
        #    - "0.0.0.0:5002:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser1
            ME_CONFIG_MONGODB_ADMINPASSWORD: topSecretDontTel!l1234
            ME_CONFIG_MONGODB_SERVER: mongodb