volumes:
    mongodb_volume:
services:
    mongodb:
        image: mongo
        restart: "unless-stopped"
        volumes:
            - mongodb_volume:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongouser1
            MONGO_INITDB_ROOT_PASSWORD: topSecretDontTel!l1234