#manage-order: 5000
version: '3.3'
services:
  nginx:
    container_name: ${DCPREFIX}_nginx
    image: nginx:stable
    ports:
      - "${ODOO_PORT}:80"
    env_file:
        - ../settings
        - ../settings.customs
    volumes:
      - ../machines/nginx/nginx_${ODOO_VERSION}.conf:/mysite.template
      - ../run/nginx_paths:/etc/nginx/paths
      - ../run/nginx_confs:/etc/nginx/conf.d
    command: /bin/bash -c "echo 'setting up nginx conf'; cp /mysite.template /etc/nginx/conf.d/default.conf && sed -i "s/__HTTP_HOST__/$HTTP_HOST/g" /etc/nginx/conf.d/default.conf && ls -lha /etc/nginx/paths && nginx -g 'daemon off;'"
