#manage-order: 5000
version: '3.3'
services:
  nginx:
    container_name: ${DCPREFIX}_nginx
    image: nginx:stable
    ports:
      - "${ODOO_PORT}:80"
    env_file:
        - ../settings
    volumes:
      - ../machines/nginx/nginx_${ODOO_VERSION}.conf:/mysite.template
      - ../run/nginx_paths:/etc/nginx/paths
      - ../run/nginx_confs:/etc/nginx/conf.d
      - ../machines/nginx/bin:/opt/bin
    command: /bin/bash /opt/bin/run.sh
