version: '2'

volumes:
  davical:
  davical_db:

services:
  davical:
    container_name: ${DCPREFIX}_davical
    build: $ODOO_HOME/machines/davical
    depends_on:
      - davical_db
    ports:
      - "8200:80"
      - "3333:3333"
    volumes:
        - $ODOO_HOME/machines/davical/conf:/config
        - davical:/var/www/html
        - $ODOO_HOME/machines/davical/src:/opt/src
        - $ODOO_HOME/machines/davical/admin.py:/opt/admin.py
    environment:
        PHP_VERSION: 7.0.10
        PGPASSWORD: davical
        PSQLOPTS: -h davical_db -U davical
        AWL_DBAUSER: davical
        AWL_DBNAME: davical
        AWL_APPUSER: davical
        INITIAL_ADMIN_PASSWORD: davicaladmin_!!
        DBHOST: davical_db
        DBPORT: 5432
        DBAOPTS: --dbhost davical_db --dbuser davical
        SRC_DIR: /opt/src_filemodeupdated
  davical_db:
    container_name: ${DCPREFIX}_davical_db
    image: postgres:9.6.6
    volumes:
        - davical_db:/data
        - $ODOO_HOME/machines/davical/add_users.sql:/docker-entrypoint-initdb.d/add_users.sql
    environment:
        POSTGRES_PASSWORD: davical
        POSTGRES_USER: davical
        POSTGRES_DB: postgres
        PGDATA: /data
