# manage-order 1000
version: '3.3'

services:
  odoo_base: &odoo_base
    container_name: ${DCPREFIX}_odoo_base
    build:
        context: ../machines/odoo
        args:
          ODOO_VERSION: ${ODOO_VERSION}
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - DAC_READ_SEARCH
    volumes:
      - ../dumps:/opt/dumps
      - ../run/restore:/opt/restore
      - ${ODOO_FILES}/:/opt/files
      - ../admin:/opt/odoo/admin
      - ../data/src/customs/${CUSTOMS}:/opt/odoo/active_customs
      - ../run/odoo_debug.txt:/tmp/odoo_debug.txt
    env_file:
      - ../settings
      - ../machines/odoo/docker-env
    command: echo 'odoo_base - good bye - it is ok!'

  odoo:
    <<: *odoo_base
    container_name: ${DCPREFIX}_odoo
    environment:
      DEBUGGER_WATCH: /tmp/odoo_debug.txt
      DEBUGGER_ODOO_PID: /tmp/odoo.debug.pid
    command: /rootrun.sh
    ports:
       - "8072:8072"

  odoo_debug:
    <<: *odoo_base
    container_name: ${DCPREFIX}_odoo_debug
    environment:
      DEBUGGER: 1
      DEBUGGER_WATCH: /tmp/odoo_debug.txt
      DEBUGGER_ODOO_PID: /tmp/odoo.debug.pid
    command: /rootrun.sh
    ports:
       # alphaphrase of debug
       - "33284:8072"
      
  odoo_cronjobs:
    <<: *odoo_base
    container_name: ${DCPREFIX}_odoo_cronjobs
    environment:
      IS_ODOO_CRONJOB: 1
    command: /rootrun.sh

  odoo_update:
    <<: *odoo_base
    container_name: ${DCPREFIX}_odoo_updater
    # called by manage.sh
    command: echo 'good bye - it is ok!'

