# manage-order 1000
version: '3.3'

services:
  admin:
    container_name: ${DCPREFIX}_admin
    build: $ODOO_HOME/machines/admin
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - $ODOO_HOME/machines/admin/src:/opt/src
      - /var/run/docker.sock:/var/run/docker.sock
      - $ODOO_HOME:/opt/odoo
      - $ODOO_HOME/machines/odoo/bin/update_modules.sh:/update_modules.sh
    environment:
        DBNAME: admin
        LOGLEVEL: info
        INSTANCES_FILE: /opt/odoo/run/odoo_instances
        ODOO_HOME: /opt/odoo
        HOST_ODOO_HOME: $ODOO_HOME
        DCPREFIX: $DCPREFIX
        MINIMUM_CONTAINERS: nginx,redis
        DEPLOY_BRANCH: deploy
        MASTER_BRANCH: master
    env_file:
      - $ODOO_HOME/settings
    command: /rootrun.sh
    ports:
       - "4488:8069"
