# so that ./manage.sh attach {machinename} works: container_name == prefix + service-name
version: '2'
volumes:
  mailstorage:
  mailsqlite:

services:

  # public mail server can receive mails
  mail:
    container_name: ${DCPREFIX}_mail
    build: ../machines/mail
    volumes:
      - mailstorage:/home/postmaster/Maildir
      - mailsqlite:/rc
    ports:
      - "${SMTP_PORT}:25"

  roundcube:
    container_name: ${DCPREFIX}_roundcube
    build: ../machines/roundcube
    ports:
      - "${ROUNDCUBE_PORT}:80"
    environment:
      MAIL_SERVER: mail

  # internal mail server to check outgoing odoo mails
  roundcube_check_sent_mails:
    container_name: ${DCPREFIX}_roundcube_check_sent_mails
    build: ../machines/roundcube
    environment:
      MAIL_SERVER: mail_check_sent_mails

  mail_check_sent_mails:
    container_name: ${DCPREFIX}_mail_check_sent_mails
    build: ../machines/mail
    volumes:
      - ../data/mail/odoo_sent_mails/maildir:/home/postmaster/Maildir
      - ../data/mail/odoo_sent_mails/sqlite:/rc
