# so that ./manage.sh attach {machinename} works: container_name == prefix + service-name
version: '2'
volumes:
  arisourcestorage:
  stasissourcestorage:
  asterisk_logs:

services:
  dns:
      build: ../machines/openvpn/openvpn_dns
      cap_add:
        - NET_ADMIN
      volumes:
        - ../data/ovpn/client:/opt/certs:ro

  ntp:
      build: ../machines/openvpn/openvpn_ntp
      cap_add:
        - NET_ADMIN
      volumes:
        - ../data/ovpn/client:/opt/certs:ro
      ports:
        - "${NTP_PORT}:123/UDP"

  ovpn_ca:
    container_name: ${DCPREFIX}_ovpn_ca
    build: ../machines/openvpn/openvpn_ca
    volumes:
        - ../config/ovpn/:/root/confs:ro
        - ../data/ovpn/CA/keys:/root/openvpn-ca/keys
        - ../data/ovpn/CA:/root/transfer
        - ../data/ovpn/server:/root/server_out
        - ../data/ovpn/client:/root/client_out
    env_file:
      - ../customs.env
    command: echo 'exiting'

  ovpn_makekeys:
    container_name: ${DCPREFIX}_ovpn_makekeys
    build: ../machines/openvpn/openvpn_server
    volumes:
        - ../config/ovpn:/root/input/confs:ro
        - ../data/ovpn/CA/keys:/root/openvpn-ca/keys:ro
        - ../data/ovpn/server:/root/server_out
        - ../data/ovpn/client:/root/client_out
        - ../config/ovpn/ccd:/root/ccd
    env_file:
      - ../customs.env
    command: echo 'exiting'

  ovpn:
    container_name: ${DCPREFIX}_ovpn
    build: ../machines/openvpn/openvpn_server
    ports:
        - "${OVPN_PORT}:1194/TCP"
        - "${OVPN_PORT}:1194/UDP"
    volumes:
        - ../config/ovpn:/root/confs:ro
        - ../data/ovpn/CA/keys:/root/openvpn-ca/keys:ro
        - ../data/ovpn/server:/root/server_out
        - ../data/ovpn/client:/root/client_out
        - ../config/ovpn/ccd:/tmp/ccd:ro

    env_file:
      - ../customs.env
    cap_add:
        - NET_ADMIN
    command: /root/tools/run.sh

  ovpn_web:
    container_name: ${DCPREFIX}_odoo_ovpn_web
    build: ../machines/openvpn/openvpn_web
    ports:
        - "${OVPNWEB_PORT}:8080"
    volumes:
        - ../data/ovpn/client:/root/transfer:ro
        - ../config/ovpn:/root/config:ro
    command: python3 /root/tools/monjerri.py
