version: '2'
services:
  odoo:
    environment:
      DO_UPDATE: 1
  asterisk:
    environment:
      DO_UPDATE: 1
  asterisk_ari:
    environment:
      DO_UPDATE: 1
  mail:
    command: echo 'done'
  roundcube:
    command: echo 'done'
  postgres:
    command: echo 'done'
