# manage-order: 5000
# so that ./manage.sh attach {machinename} works: container_name == prefix + service-name
version: '3.3'
volumes:
  mailstorage:
  mailsqlite:

services:

  # public mail server can receive mails
  mail:
    container_name: ${DCPREFIX}_mail
    build: $HOST_ODOO_HOME/machines/mail
    volumes:
      - mailstorage:/home/postmaster/Maildir
      - mailsqlite:/rc
      - $HOST_ODOO_HOME/machines/mail/bin:/opt/bin
    ports:
      - "${SMTP_PORT}:25"

  roundcube:
    container_name: ${DCPREFIX}_roundcube
    build: $HOST_ODOO_HOME/machines/roundcube
    ports:
      - "${ROUNDCUBE_PORT}:80"
    environment:
      MAIL_SERVER: mail

  # internal mail server to check outgoing odoo mails
  roundcube_check_sent_mails:
    container_name: ${DCPREFIX}_roundcube_check_sent_mails
    build: $HOST_ODOO_HOME/machines/roundcube
    environment:
      MAIL_SERVER: mail_check_sent_mails

  mail_check_sent_mails:
    container_name: ${DCPREFIX}_mail_check_sent_mails
    build: $HOST_ODOO_HOME/machines/mail
    volumes:
      - $HOST_ODOO_HOME/data/mail/odoo_sent_mails/maildir:/home/postmaster/Maildir
      - $HOST_ODOO_HOME/data/mail/odoo_sent_mails/sqlite:/rc
