# manage-order: 5000
# so that ./manage.sh attach {machinename} works: container_name == prefix + service-name
version: '3.3'
volumes:
  ${CUSTOMS}_mailstorage:
  ${CUSTOMS}_mailsqlite:

services:

  # public mail server can receive mails
  mail:
    container_name: ${CUSTOMS}_mail
    build: $ODOO_HOME/machines/mail
    volumes:
      - ${CUSTOMS}_mailstorage:/home/postmaster/Maildir
      - ${CUSTOMS}_mailsqlite:/rc
      - $ODOO_HOME/machines/mail/bin:/opt/bin
    ports:
      - "${SMTP_PORT}:25"

  roundcube:
    container_name: ${CUSTOMS}_roundcube
    build: $ODOO_HOME/machines/roundcube
    ports:
      - "${ROUNDCUBE_PORT}:80"
    environment:
      MAIL_SERVER: mail

  # internal mail server to check outgoing odoo mails
  roundcube_check_sent_mails:
    container_name: ${CUSTOMS}_roundcube_check_sent_mails
    build: $ODOO_HOME/machines/roundcube
    environment:
      MAIL_SERVER: mail_check_sent_mails

  mail_check_sent_mails:
    container_name: ${CUSTOMS}_mail_check_sent_mails
    build: $ODOO_HOME/machines/mail
    volumes:
      - $ODOO_HOME/data/mail/odoo_sent_mails/maildir:/home/postmaster/Maildir
      - $ODOO_HOME/data/mail/odoo_sent_mails/sqlite:/rc
