# manage-order: 5000
version: '3.3'
volumes:
  mailstorage:
  mailsqlite:

services:
  mail:
    build: $ODOO_HOME/images/mail
    volumes:
      - mailstorage:/home/postmaster/Maildir
      - mailsqlite:/rc
      - $ODOO_HOME/images/mail/bin:/opt/bin

  roundcube:
    build: $ODOO_HOME/images/roundcube
    ports:
      - "${ROUNDCUBE_IP}:${ROUNDCUBE_PORT}:80"
    environment:
      MAIL_SERVER: ${PROJECT_NAME}_mail
