# borrowed from tiredofit
version: '3.7'

services:
    connector-mqtt-asterisk:
        build: ../connector_mqtt_asterisk
        volumes:
            # better debugging
            - ../connector_mqtt_asterisk/app.py:/app.py:ro
        environment:
            # must be unique - client id of mqtt client, otherwise no registration
            - APP_NAME=asterisk_connector_test
            - MQTT_BROKER_HOST=DOCKER_HOST
            - MQTT_BROKER_PORT=1883
            - ASTERISK_SERVER=DOCKER_HOST
            - ASTERISK_ARI_PORT=8088
            - ASTERISK_ARI_USER=ariuser1
            - ASTERISK_ARI_PASSWORD=password1
            - ASTERISK_AMI_USER=an_ami_user2
            - ASTERISK_AMI_PASSWORD=a_password
            - ASTERISK_AMI_PORT=5038
            - ASTERISK_SSH_PORT=9022

    freepbx:
        container_name: freepbx-app
        build: docker-freepbx
        ports:
            - 9080:80
            - "9022:22"
            - 8088:8088
            - 5038:5038
            - "5060:5060/tcp"
            - "5060:5060/udp"
            - 5160:5160
            - "10000-10200:10000-10200/udp"
            - 4445:4445
        environment: 
            # must match above
            - ASTERISK_ARI_USER=ariuser1
            - ASTERISK_ARI_PASSWORD=password1
            - ASTERISK_AMI_USER=an_ami_user2
            - ASTERISK_AMI_PASSWORD=a_password

            - RTPSTART=10000
            - RTPEND=10200
            # set by run_freepbx
            - EXTERNIP

            - UCP_FIRST=False
