# borrowed from tiredofit
version: '3.7'

services:
    connector-mqtt-ariami:
        build: ../connector_mqtt_ariami
        volumes:
            # better debugging
            - ../connector_mqtt_ariami/app.py:/app.py:ro
        environment:
            # must be unique - client id of mqtt client, otherwise no registration
            - APP_NAME=asterisk_connector_test
            - MQTT_BROKER_HOST=DOCKER_HOST
            - MQTT_BROKER_PORT=1883
            - ASTERISK_SERVER=freepbx-app
            - ASTERISK_ARI_PORT=8088
            - ASTERISK_ARI_USER=ariuser1
            - ASTERISK_ARI_PASSWORD=password1
            - ASTERISK_AMI_USER=an_ami_user2
            - ASTERISK_AMI_PASSWORD=a_password
            - ASTERISK_AMI_PORT=5038

    freepbx-app:
        container_name: freepbx-app
        build: docker-freepbx
        ports:
            - 9080:80
            - 8088:8088
            - 5038:5038
            - 5060:5060
            - 5160:5160
            - 18000-18100:18000-18100/udp
            - 4445:4445
        environment: 
            # must match above
            - ASTERISK_ARI_USER=ariuser1
            - ASTERISK_ARI_PASSWORD=password1
            - ASTERISK_AMI_USER=an_ami_user2
            - ASTERISK_AMI_PASSWORD=a_password

            - UCP_FIRST=False
            - VIRTUAL_HOST=hostname.example.com
            - VIRTUAL_NETWORK=nginx-proxy
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=hostname.example.com
            - LETSENCRYPT_EMAIL=email@example.com

            - ZABBIX_HOSTNAME=freepbx-app

            - RTP_START=18000
            - RTP_FINISH=18100
    
        restart: always
        privileged: true
