version: '3.7'
services:
  cicd_delegator:
    build: ./cicd_delegator
    #volumes:
    #    # cicd delegator is stored in ~/.odoo/cicd_delegator globally
    #    - ./empty:/etc/nginx/conf.d/default.conf
    #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #    - ./nginx.upstreams.conf:/etc/nginx/conf.d/upstreams.conf:ro
    #    - ./nginx.locations.conf:/etc/nginx/conf.locations.d/locations.conf:ro
    ports:
        - __CICD_BINDING__:80
    networks:
        - cicd_delegator
    volumes:
        - ./registry.json:/registry.json
  cicd_test:
    build: ./cicd_tester
    networks:
        - cicd_delegator
    command: "bash -c 'while true; do sleep 1;done'"
  cicd_index:
    build: ./cicd_index
    networks:
        - cicd_delegator
    environment:
        FLASK_ENV: development
    volumes:
        - ./registry.json:/registry.json
networks:
    cicd_delegator:
        name: __CICD_NETWORK_NAME__
