version: '3.7'
services:
  cicd_delegator:
    build: ./cicd_delegator
    ports:
        - __CICD_BINDING__:80
    networks:
        - cicd_delegator
    environment:
        REGISTRY_SITES: /registry_sites
    volumes:
        - ./registry.json:/registry.json
        - ./registry_sites:/registry_sites
    restart: "unless-stopped"
  cicd_test:
    build: ./cicd_tester
    networks:
        - cicd_delegator
    command: "bash -c 'while true; do sleep 1;done'"
  cicd_index:
    build: ./cicd_index
    networks:
        - cicd_delegator
    restart: "unless-stopped"
    environment:
        FLASK_ENV: development
        REGISTRY_SITES: /registry_sites
        DISPLAY_TIMEZONE: Europe/Berlin
        DATE_FORMAT: '_d._m._Y _H:_M:_S'
    volumes:
        - ./registry.json:/registry.json
        - ./registry_sites:/registry_sites
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
networks:
    cicd_delegator:
        name: __CICD_NETWORK_NAME__
