#manage-order: 5000
version: '2.1'
volumes:
  asterisk_logs:

services:
  asterisk_redis:
      build: ../machines/asterisk/redis
      container_name: ${DCPREFIX}_asterisk_redis
  ari:
    container_name: ${DCPREFIX}_ari
    build: ../machines/asterisk/ari
    depends_on:
      - asterisk_redis
    ports:
        - "29926:29926"
    environment:
      ODOO_USER: $ASTERISK_ODOO_USER
      ODOO_PASSWORD: $ASTERISK_ODOO_PASSWORD
      ODOO_DB: $DBNAME
      ODOO_PORT: 8072
      ODOO_HOST: odoo
      USERNAME_ASTERISK: asterisk
      PASSWORD_ASTERISK: asterisk
      HOST_ASTERISK: asterisk
      PORT_ASTERISK: 8088
      PROXY_PORT_IN: 29926
      PROXY_PORT_OUT: 80
    volumes:
      - odoosource:/opt/odoo
      - ../data/ari/calls:/opt/permstore/calls
      - ../data/ari/uploaded_calls:/opt/permstore/uploaded_calls
      - ../data/ari/record_clicked:/opt/permstore/record_clicked
      - ../data/asterisk/moh_custom:/opt/asterisk/moh_custom
      - ../data/asterisk/recordings:/opt/asterisk/recording
      - ../data/asterisk/reloader:/opt/asterisk/reloader
      - ../data/asterisk/sounds:/opt/asterisk/sounds
      - ../machines/asterisk/asterisk/etc/asterisk:/opt/asterisk/etc
    env_file:
      - ../settings

  stasis:
      build: ../machines/asterisk/stasis
      container_name: ${DCPREFIX}_stasis
      environment:
        PROXY_PORT_IN: 28121
        PROXY_PORT_OUT: 80
      env_file:
        - ../settings
      depends_on:
        - asterisk
        - asterisk_redis
      volumes:
        - ../data/src/customs/${CUSTOMS}/common/asterisk_ari/stasis:/opt/src:ro
        - ../data/asterisk/reloader:/opt/reloader
        - asterisk_logs:/var/log/asterisk

  asterisk:
    container_name: ${DCPREFIX}_asterisk
    depends_on:
        ovpn:
            condition: service_healthy
    build: ../machines/asterisk/asterisk
    expose:
      - 8088
    environment:
      CUSTOMS: ${CUSTOMS}
    volumes:
      - ../machines/asterisk/asterisk/etc/asterisk:/etc/asterisk:ro
      - ../data/ovpn/client:/opt/certs:ro
      - ../data/asterisk/moh_custom:/var/lib/asterisk/moh_custom:ro
      - ../data/asterisk/recordings:/var/spool/asterisk/recording
      - ../data/asterisk/reloader:/opt/reloader
      - ../data/asterisk/sounds:/var/lib/asterisk/sounds:ro
      - asterisk_logs:/var/log/asterisk
    env_file:
      ../settings
    cap_add:
        - NET_ADMIN
    healthcheck:
        test: ["CMD-SHELL", "/root/tools/healthcheck.sh"]
        interval: 15s
        timeout: 5s
        retries: 2

