#manage-order: 5000
version: '3.3'
volumes:
  asterisk_logs:

services:
  asterisk_redis:
      build: $HOST_ODOO_HOME/machines/asterisk/redis
      container_name: ${DCPREFIX}_asterisk_redis
  ari:
    container_name: ${DCPREFIX}_ari
    build: $HOST_ODOO_HOME/machines/asterisk/ari
    depends_on:
      - asterisk_redis
    ports:
      - "8812:80"
      - "29926:29926"
    environment:
      ODOO_USER: $ASTERISK_ODOO_USER
      ODOO_PASSWORD: $ASTERISK_ODOO_PASSWORD
      ODOO_DB: $DBNAME
      ODOO_PORT: 8072
      ODOO_HOST: odoo
      USERNAME_ASTERISK: asterisk
      PASSWORD_ASTERISK: asterisk
      HOST_ASTERISK: asterisk
      PORT_ASTERISK: 8088
      PROXY_PORT_IN: 29926
      PROXY_PORT_OUT: 80
    volumes:
      - ${HOST_ODOO_HOME}/data/src/customs/${CUSTOMS}:/opt/odoo/active_customs
      - $HOST_ODOO_HOME/data/ari/calls:/opt/permstore/calls
      - $HOST_ODOO_HOME/data/ari/uploaded_calls:/opt/permstore/uploaded_calls
      - $HOST_ODOO_HOME/data/ari/record_clicked:/opt/permstore/record_clicked
      - $HOST_ODOO_HOME/data/asterisk/moh_custom:/opt/asterisk/moh_custom
      - $HOST_ODOO_HOME/data/asterisk/recordings:/opt/asterisk/recording
      - $HOST_ODOO_HOME/data/asterisk/reloader:/opt/asterisk/reloader
      - $HOST_ODOO_HOME/data/asterisk/sounds:/opt/asterisk/sounds
      - $HOST_ODOO_HOME/machines/asterisk/asterisk/etc/asterisk:/opt/asterisk/etc
    env_file:
      - $HOST_ODOO_HOME/settings
      - $HOST_ODOO_HOME/settings.override

  stasis:
      build: $HOST_ODOO_HOME/machines/asterisk/stasis
      container_name: ${DCPREFIX}_stasis
      environment:
        PROXY_PORT_IN: 28121
        PROXY_PORT_OUT: 80
      env_file:
        - $HOST_ODOO_HOME/settings
      depends_on:
        - asterisk
        - asterisk_redis
      volumes:
        - $HOST_ODOO_HOME/data/src/customs/${CUSTOMS}/common/asterisk_ari/stasis:/opt/src:ro
        - $HOST_ODOO_HOME/data/asterisk/reloader:/opt/reloader
        - asterisk_logs:/var/log/asterisk

  asterisk:
    container_name: ${DCPREFIX}_asterisk
    depends_on:
        - asterisk_ovpn_server
    build:
        context: $HOST_ODOO_HOME/machines/asterisk/asterisk
        args:
            - ASTERISK_COUNTRY_ITU=${ASTERISK_COUNTRY_ITU}
    environment:
      TRIGGER: /opt/reloader/reload
    volumes:
      - $HOST_ODOO_HOME/run/asterisk/etc:/etc/asterisk:ro
      - $HOST_ODOO_HOME/data/ovpn/client:/opt/certs:ro
      - $HOST_ODOO_HOME/data/asterisk/moh_custom:/var/lib/asterisk/moh_custom:ro
      - $HOST_ODOO_HOME/data/asterisk/recordings:/var/spool/asterisk/recording
      - $HOST_ODOO_HOME/data/asterisk/reloader:/opt/reloader
      - $HOST_ODOO_HOME/data/asterisk/sounds:/var/lib/asterisk/sounds:ro
      - asterisk_logs:/var/log/asterisk
    env_file:
        - $HOST_ODOO_HOME/settings
        - $HOST_ODOO_HOME/settings.override
    cap_add:
        - NET_ADMIN
    healthcheck:
        test: ["CMD-SHELL", "/root/tools/healthcheck.sh"]
        interval: 15s
        timeout: 5s
        retries: 2
