version: "3.3"
services:
  simplebash:
    image: ${PROJECT_NAME}_simplebash
    privileged: true
    volumes:
      - $WORKING_DIR:/WORKING_DIR
      - /var/run/docker.sock:/var/run/docker.sock
      - /run:/host/run
      - /run/docker/plugins:/run/docker/plugins
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME:/opt/external_home
      - /root:/root
      - /etc:/etc_host:ro
      # Parallels compatible
      - /media/psf/Home/:/media/psf/Home:ro
    working_dir: $HOME
    environment:
      - DOCKER_BASH=1
      - LOCAL_ODOO_HOME=/opt/odoo
      - ODOO_HOME
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - ODOO_UPDATE_START_NOTIFICATION_TOUCH_FILE_IN_CONTAINER=/tmp/timestamp_update/timestamp
      - PROJECT_NAME
      - NETWORK_NAME
      - HOST_HOME
      - HOST_ODOO_HOME
      - DUMPS_PATH
      - DUMPS_PATH_GID
      - TZ
    entrypoint: /entrypoint.sh
    hostname: $HOSTNAME_TO_USE

networks:
    default:
        external:
            name: ${NETWORK_NAME}
