version: "3.3"
services:
  simplebash:
    build: .
    volumes:
      - $ODOO_HOME:$ODOO_HOME
      - /:/ROOT
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME:/opt/external_home
    working_dir: $HOME
    environment:
      - EXTERNAL_ROOT=/ROOT
      - DOCKER_BASH=1
      - ODOO_HOME
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    entrypoint: /entrypoint.sh
    env_file:
      - ../../settings
      - ../../settings.override
    hostname: $HOSTNAME_TO_USE
networks:
    default:
        external:
            name: ${PROJECT_NAME}_default
