version: "3.3"
services:
  simplebash:
    build: .
    volumes:
      - $DIR:$DIR
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_BASH: 1
      ODOO_HOME: /opt/odoo
    entrypoint: /entrypoint.sh
    env_file:
      - ../../settings
      - ../../settings.override
