version: "3.3"
services:
  simplebash:
    build: .
    volumes:
      - $DIR:$DIR
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME:$HOME
    working_dir: $HOME
    environment:
      - DOCKER_BASH=1
      - ODOO_HOME=/opt/odoo
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - USER=$USER
    entrypoint: /entrypoint.sh
    env_file:
      - ../../settings
      - ../../settings.override
    hostname: $HOSTNAME_TO_USE
