version: "3.3"
services:
  simplebash:
    build: .
    volumes:
      - $ODOO_HOME:$ODOO_HOME
      # - /:/ROOT  never mount root / problems on older kernels and system (device or resource busy)
      - $WORKING_DIR:/WORKING_DIR
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME:/opt/external_home
      - $ODOO_UPDATE_START_NOTIFICATION_TOUCH_FILE_PATH:/tmp/timestamp_update/
    working_dir: $HOME
    env_file:
      - ../../settings
      - ../../settings.override
    environment:
      - DOCKER_BASH=1
      - ODOO_HOME
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - ODOO_UPDATE_START_NOTIFICATION_TOUCH_FILE_IN_CONTAINER=/tmp/timestamp_update/timestamp
    entrypoint: /entrypoint.sh
    hostname: $HOSTNAME_TO_USE
networks:
    default:
        external:
            name: ${PROJECT_NAME}_default
