version: "3.3"
services:
  simplebash:
    build: .
    volumes:
      - $ODOO_HOME:/opt/odoo
      - $ODOO_HOME:$ODOO_HOME  # trying to get rid of this; odoo build says: build path /home/marc/odoo/machines/mail either does not exist, is not accessible, or is not a valid URL
      # - /:/ROOT  never mount root / problems on older kernels and system (device or resource busy)
      - $WORKING_DIR:/WORKING_DIR
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME:/opt/external_home
      - /root:/root
      - /etc:/etc_host:ro
    working_dir: $HOME
    environment:
      - DOCKER_BASH=1
      - LOCAL_ODOO_HOME=/opt/odoo
      - ODOO_HOME
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - ODOO_UPDATE_START_NOTIFICATION_TOUCH_FILE_IN_CONTAINER=/tmp/timestamp_update/timestamp
    entrypoint: /entrypoint.sh
    hostname: $HOSTNAME_TO_USE

  cron:
    build: .
    container_name: ${PROJECT_NAME}_cron
    volumes:
      - $ODOO_HOME:/opt/odoo
      - /var/run/docker.sock:/var/run/docker.sock
      - $DUMPS_PATH:/host/dumps
    env_file: /opt/odoo/run/settings
    environment:
      - DOCKER_BASH=1
      - LOCAL_ODOO_HOME=/opt/odoo
      - ODOO_HOME
      - NETWORK_NAME
      - PROJECT_NAME
      - HOST_HOME
      - DOCKER_GROUP_ID
      - PLATFORM
      - UID
      - SSH_CONNECTION
    entrypoint: /entrypoint.sh
    restart: unless-stopped
    command: ["/opt/odoo/admin/odoo-admin", "execute"]

networks:
    default:
        external:
            name: ${NETWORK_NAME}
