version: "3.3"
services:
  cron:
    image: ${PROJECT_NAME}_simplebash
    container_name: ${PROJECT_NAME}_cron
    volumes:
      - /etc:/etc_host:ro
      - $ODOO_HOME:/opt/odoo
      - $HOST_ODOO_HOME:$HOST_ODOO_HOME
      - /var/run/docker.sock:/var/run/docker.sock
      - $DUMPS_PATH:/host/dumps
    env_file: /opt/odoo/run/settings
    environment:
      - DOCKER_BASH=1
      - CRON_CONTAINER=1
      - LOCAL_ODOO_HOME=/opt/odoo
      - ODOO_HOME
      - NETWORK_NAME
      - PROJECT_NAME
      - HOST_HOME
      - DOCKER_GROUP_ID
      - PLATFORM
      - UID
      - SSH_CONNECTION
      - PERSIST_JOBBER_ENV_VARIABLES=PROJECT_NAME,ODOO_HOME,CUSTOMS
    entrypoint: /entrypoint.sh
    restart: 'unless-stopped'
    command: ["/opt/odoo/admin/odoo-admin", "execute"]

networks:
    default:
        external:
            name: ${NETWORK_NAME}
