# manage-order: 5000
# so that ./manage.sh attach {machinename} works: container_name == prefix + service-name
version: '3.3'
volumes:
  ${PROJECT_NAME}_${CUSTOMS}_mosquitto_logs:
  ${PROJECT_NAME}_${CUSTOMS}_mosquitto_data:

services:

  # public mail server can receive mails
  mosquitto:
    container_name: ${PROJECT_NAME}_${CUSTOMS}_mosquitto
    build: $ODOO_HOME/machines/mosquitto
    volumes:
        - $ODOO_HOME/machines/mosquitto/config:/mqtt/config
        - ${PROJECT_NAME}_${CUSTOMS}_mosquitto_logs:/mqtt/logs
        - ${PROJECT_NAME}_${CUSTOMS}_mosquitto_data:/mqtt/data
    ports:
        - "1883:1883"
        - "9001:9001"
